### ISSUE TITLE
Android drawable directory.

### ISSUE THREAD

**Issue by chenenyu** [ozzik/Slicer#5]
It's usually "mipmap", not "drawable".

**Comment by ozzik** [comment]
Hey there and thanks for reaching out!

According to [Google](http://android-developers.blogspot.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html) (and the almighty ["supporting multiple screens"](https://developer.android.com/guide/practices/screens_support.html) documentation) , `mipmap`directories are for the launch icons and the `drawable` ones are for the actual app assets :)

But anyway, hoping Slicer's next version would include customizing the name of the folders or at least selecting between exporting launcher icons vs. graphic assets :P
