### ISSUE TITLE
Export with transparent canvas

### ISSUE THREAD

**Issue by girafic** [ozzik/Slicer#6]
Please add the option to export assets with transparent canvas without creating slices.

![bildschirmfoto 2016-11-10 um 08 52 16](https://cloud.githubusercontent.com/assets/1187276/20168582/3e34c420-a723-11e6-9acd-3fe90b56807f.png)

**Comment by illustree** [comment]
without using sketch slices would be a huge improvement ... please add the functionality that when exporting, the plugin would ...

either ...
A. export the slice (as is now)
or ...
B. if I selected the group just export the entire group (in that case Slicer would not ignore the transparent layers)

**Comment by girafic** [comment]
check #9

**Comment by Greghster** [comment]
Agreed

**Comment by Greghster** [comment]
I have the same problem

**Comment by ozzik** [comment]
Fixed with @girafic awesome fix! Pushed to 0.4.2 :)
